### ISSUE TITLE
Sprungverhalten nicht korekt/exakt

### ISSUE THREAD

**Issue by Wombat2018** [hubsif/kodi-magentasport#28]
Hallo,

ich habe wegen des EuroLeague Final Fours nach sehr langer Zeit mal wieder Magenta Sport genutzt und erstmals dieses Addon hier. Dabei fiel mir folgendes auf:
Ich habe alles relive, also als Wiederholung geschaut:
- Zurückspringen um 10 Sekunden springt überhaupt nicht zurück
- Zurückspringen um 30 Sekunden springt 23-25 Sekunden zurück
- Zurückspringen um 60 Sekunden springt 50 Sekunden zurück

Für Vorwärtsspringen sind 10 Sekunden noch exakt, aber bei 30 und 60 Sekunden wird auch etwas zu weit nach vorne gesprungen.

In anderen Streaming-Addons, z.B. DAZN und Zattoo, funktioniert das Vorwärts- und Rückwärtsspringen exakt.

**Comment by hubsif** [comment]
Hi!
Die Antwort kommt zwar etwas später, dennoch:
Für jegliches Verhalten welches das Video Playback betrifft, ist das Addon nicht verantwortlich und kann es auch nicht beeinflussen. Es übergibt letztlich lediglich eine Streaming-URL an Kodi, welches entsprechend damit umgehen muss.
Dass es bei DAZN, Zatoo, ... funktioniert kann daran liegen, dass andere Streaming-Techniken zum Einsatz kommen. Möglicherweise ist es auch mittlerweile in Kodi behoben.
