### ISSUE TITLE
Geht nicht mehr

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-magentasport#29]
Geht wo BBL gerade?

**Comment by MRLB** [comment]
War ein Telekom Login Problem

**Comment by vanso-hubsi** [comment]
Hi @MRLB,
Ich nutze mal diesen ausgefallenen Weg mit dir zu kommunizieren. Github hat ja leider keinen "chat".

Wie sicherlich alle gemerkt haben ist dieses Plugin "unmaintained", ich habe keine Zeit und Muse (und auch keinen Account) mehr es weiter zu betreeuen.
Nachdem du deinen Fork ja immer schön weitergepflegt hast, wollte ich dich fragen, ob du das übernehmen magst. Entweder indem ich in der README auf deinen Fork verweise. Oder alternativ kann ich dir auch die Rechte für das Repo hier geben.
Ich hab auch herausgefunden, dass es scheinbar noch ein anderes Magentasport-Addon u.a. in Kodinerds gibt (ist wohl auch über das beliebte Ghost repo verfügbar). Ich weiß nicht, ob das aktueller/besser ist. Zur Not verweise ich einfach auf das.

Überlegs dir, freue mich auf eine kurze Antwort!

**Comment by MRLB** [comment]
hallo @hubsif,
klar, du kannst im README gerne auf meinen Fork verweisen.
Das Kodinerds-Addon funktioniert auch gut. ich habe beide bei mir drauf, damit wenn das eine mal nicht mag, noch ein Backup habe ;-)
