### ISSUE TITLE
Livestreams starten nichts in Liveprogramm

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-magentasport#31]
Seit kurzem muss ich bei vielen Livestreams erst 3/4 Stunden vorspulen um ins Livebild zu kommen. Ist dies ein Addon-problem oder wiedermal eein Telekom-problem?

Danke

**Comment by FynnSchapdick** [comment]
Selbes Problem, das merkwürdige dabei ist, es betrifft nicht jeden Stream

**Comment by hubsif** [comment]
Hi!
Das Addon kümmert sich nicht selbst um das Abspielen der Streams, sondern stellt diese nur Kodi bereit. Falls dann damit was nicht passt, ist das leider ein Kodi- oder wahrscheinlicher ein Telekom-Problem.
