### ISSUE TITLE
No video works anymore

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-magentasport#39]
Unfortunately no video works anymore. Is it possible to check it?

**Comment by hubsif** [comment]
Please have a look at #38, which has recently been opened. I'll merge and create new releases soon.

**Comment by MRLB** [comment]
There is also a change in the authorization :-(

**Comment by uhafner** [comment]
#38 helps for free streams. But payed streams seem to require a different handling now.

**Comment by betacentauri** [comment]
I don’t use this plugin. I have an own for enigma2 boxes. There now playback works again with this change.
As already written to MRLB it might be that also the heartbeat URL is not working anymore. I don’t use the heartbeat URL. It’s not necessary to call it.

**Comment by hubsif** [comment]
Hi!
Unfortunetaly, I don't have a paid account anymore (perhaps someone can share theirs for testing? 😬 🤐), so I'm actually not able to test this :-( .
If it's related to the heartbeat url, I think the log might reveal more. Can someone please share?

**Comment by uhafner** [comment]
Here is a log:

[kodi.log.zip](https://github.com/hubsif/kodi-magentasport/files/6637413/kodi.log.zip)

1. I started a video without `pay` option
2. I started a video with `pay` option

The version I am using is v2.1.2-beta Kodi 19 (Python 3) (with the patch of #38).

If that does not help, we I can share credentials (via Email) for a test.

**Comment by betacentauri** [comment]
Most likely the heartbeat URL:
https://github.com/hubsif/kodi-magentasport/blob/master/default.py#L89

Please try to comment out lines 257-266 (https://github.com/hubsif/kodi-magentasport/blob/master/default.py#L257-L266)
Just put a # in front of the lines
As said calling the heartbeat URL is not necessary.

**Comment by uhafner** [comment]
> Please try to comment out lines 257-266 (https://github.com/hubsif/kodi-magentasport/blob/master/default.py#L257-L266)
> Just put a # in front of the lines
> As said calling the heartbeat URL is not necessary.

Yes, that worked (at least for a non live event)! Thanks!

**Comment by MRLB** [comment]
and also for live events :-) Thank you 👍

**Comment by uhafner** [comment]
Hmm, it would make sense to close this issue only when the patch is also part of the repository.

**Comment by MRLB** [comment]
you are right

**Comment by hubsif** [comment]
Hi!
So, I just created a release with the heartbeat query removed. It might have been required when I first added it, or I wanted the plugin to behave as close as possible like the app does to avoid conflicts. Please test.

**Comment by uhafner** [comment]
I can confirm, the latest beta version (for Kodi 19) works again! Thanks!
 🎉  🎉  🎉
